version: '3.5'

services:
  db01:
    build: ./db
    container_name: db01
    restart: always
    environment:
      - PG_SLAVE=db02.db-tier
    env_file:
      - ${CONFIG-config/dev}/db.env
    networks:
      - db-tier
      - default


  db02:
    build: ./db
    container_name: db02
    restart: always
    environment:
      - PG_SLAVE=db01.db-tier
    env_file:
      - ${CONFIG-config/dev}/db.env
    networks:
      - db-tier

  nc-app:
    image: nextcloud:fpm-alpine
    restart: always
    environment:
      - POSTGRES_HOST=db01
      - POSTGRES_DB=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN}
      - NC_overwriteprotocol=https
      - NC_overwritehost=${DOMAIN}
      - NC_overwritewebroot=/nextcloud
    env_file:
      - ${CONFIG-config/dev}/db.env
      - ${CONFIG-config/dev}/admin.env
    depends_on:
      - db01

  nc-web:
    build: ./web
    restart: always
    environment:
      - VIRTUAL_HOST=${DOMAIN}
    depends_on:
      - nc-app
    networks:
      - proxy-tier
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-tier"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.rule=Host(`${DOMAIN}`) && PathPrefix(`/nextcloud`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      # - "traefik.http.routers.nextcloud.tls.certresolver=mytlschallenge"
      # strip prefix
      - "traefik.http.middlewares.nc-strip-prefix.stripprefix.prefixes=/nextcloud"
      # - "traefik.http.middlewares.nc-strip-prefix.stripprefix.forceslash=true"
      - "traefik.http.routers.nextcloud.middlewares=nc-strip-prefix@docker"
      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  gitea:
    image: gitea
    restart: always
    volumes:
      - gitea:/data
    environment:
      - DOMAIN
      - ROOT_URL=https://${DOMAIN}/gitea/
      - DB_TYPE=postgres
      - DB_HOST=db01
      - DB_NAME=gitea
      - SSH_PORT=2222
      - INSTALL_LOCK=true # will trigger auto install
      - DISABLE_REGISTRATION=true # set to false to register a user
    env_file:
      - ${CONFIG-config/dev}/db.env
    depends_on:
      - db01
    networks:
      - proxy-tier
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-tier"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.rule=Host(`${DOMAIN}`) && PathPrefix(`/gitea`)"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      # strip /gitea prefix
      - "traefik.http.middlewares.gitea-strip-prefix.stripprefix.prefixes=/gitea"
      # - "traefik.http.middlewares.gitea-strip-prefix.stripprefix.forceslash=true"
      - "traefik.http.routers.gitea.middlewares=gitea-strip-prefix@docker"
      # ssh
      - "traefik.tcp.routers.gitea-ssh.entrypoints=gitea-ssh"
      - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh"
      - "traefik.tcp.routers.gitea-ssh.tls=false"
      - "traefik.tcp.services.gitea-ssh.loadbalancer.server.port=22"

  transmission:
    image: linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - ${CONFIG-config/dev}/transmission.env
    volumes:
      - transmission:/config
      - ${TRANSMISSION_DOWNLOAD-/tmp}:/downloads
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - proxy-tier
      - default
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy-tier"
        - "traefik.http.routers.transmission.entrypoints=websecure"
        - "traefik.http.routers.transmission.rule=Host(`${DOMAIN}`) && PathPrefix(`/transmission`)"
        - "traefik.http.routers.transmission.tls=true"
        - "traefik.http.services.transmission.loadbalancer.server.port=9091"

  traefik:
    image: "traefik:v2.0.0-rc3"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--global.sendAnonymousUsage=false"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.gitea-ssh.address=:22"
      - "--metrics.influxdb=${MON_NEXTCLOUD-false}"
      - "--metrics.influxdb.address=http://172.20.0.1:8186" # TODO change to host.docker.internal when https://github.com/docker/for-linux/issues/264 is solved
      - "--metrics.influxdb.protocol=http"
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy-tier

  nc-backup:
    image: "jswetzen/rsync-backup:arm32v7"
    env_file:
      - ${CONFIG-config/dev}/nc-backup.env
    volumes:
      - "${NEXTCLOUD_BACKUP_PATH-/tmp/ncbackup}:/backup"
      - "${NEXTCLOUD_BACKUP_SSH_PATH-/root/.ssh}:/root/.ssh:ro"
    networks:
      - default

volumes:
  gitea:
  transmission:

networks:
  proxy-tier:
    name: proxy-tier
  db-tier:
    name: db-tier
